<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Advice Rule</name>
  <uuid>20791ef7-b9f3-4bb5-856e-84d2ec7a3f0b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Name is defined 
then
	set the AdviceMessage of decision to "Hello " + Name + "!" + 'Weather Advice' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
