<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>dc183103-6802-457e-80fc-b293928a0bf3</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set the AdviceMessage of decision to "Sorry, we don't have enough information to provide a response"  ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
